use_frameworks!

platform :ios, '10.0'

target 'YYNetworking_Example' do
  pod 'YYNetworking', :path => '../'

  target 'YYNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
